language: node_js
node_js:
  - 9
cache:
  yarn: true
before_script:
  - yarn truffle version
script:
  - yarn truffle compile
  - yarn truffle migrate
  - yarn truffle test
  - yarn solium -d contracts/
