language: node_js
node_js:
  - 10
before_script:
  - npm install -g ganache-cli
  - truffle version
script:
  - ganache-cli > /dev/null &
  - sleep 5
  - truffle compile
  - truffle migrate --network development
  - truffle test --network development
  - solium -d contracts/
